# Generated by Django 4.2.26 on 2025-11-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Huella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iddomicilioto', models.CharField(db_index=True, help_text='Identificador único del domicilio (ej: RA150541100000000000000000000000238832)', max_length=50, unique=True)),
                ('codigopostal', models.CharField(db_index=True, help_text='Código postal (5 dígitos)', max_length=5)),
                ('provincia', models.CharField(db_index=True, help_text='Nombre de la provincia', max_length=22)),
                ('poblacion', models.CharField(db_index=True, help_text='Nombre de la población/municipio', max_length=255)),
                ('tipovia', models.CharField(help_text='Tipo de vía (CALLE, AVENIDA, PLAZA, etc.)', max_length=17)),
                ('nombrevia', models.CharField(help_text='Nombre de la vía', max_length=255)),
                ('idtecnicovia', models.CharField(blank=True, help_text='Identificador técnico de la vía', max_length=12)),
                ('numero', models.CharField(blank=True, help_text='Número de la vía', max_length=5)),
                ('bisduplicado', models.CharField(blank=True, help_text='Indicador de bis o duplicado', max_length=1)),
                ('bloquedelafinca', models.CharField(blank=True, help_text='Bloque de la finca', max_length=8)),
                ('identificadorfincaportal', models.CharField(blank=True, help_text='Identificador de finca o portal', max_length=3)),
                ('letrafinca', models.CharField(blank=True, help_text='Letra de la finca', max_length=1)),
                ('escalera', models.CharField(blank=True, help_text='Escalera del edificio', max_length=2)),
                ('planta', models.CharField(blank=True, help_text='Planta/piso', max_length=3)),
                ('mano1', models.CharField(blank=True, help_text='Primera mano/tipo de puerta', max_length=4)),
                ('mano2', models.CharField(blank=True, help_text='Segunda mano/puerta con letra o número', max_length=4)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones sobre el domicilio')),
                ('flagdummy', models.CharField(blank=True, help_text='Flag dummy para pruebas', max_length=1)),
                ('codigoinevia', models.CharField(blank=True, help_text='Código INE de la vía', max_length=5)),
                ('codigocensal', models.CharField(blank=True, help_text='Código censal', max_length=10)),
                ('codigopai', models.CharField(blank=True, help_text='Código PAI (Padron de Asignación de Infraestructura)', max_length=18)),
                ('codigoolt', models.CharField(blank=True, db_index=True, help_text='Código OLT (Optical Line Terminal)', max_length=23)),
                ('codigocto', models.CharField(blank=True, db_index=True, help_text='Código CTO (Central Terminal Office)', max_length=15)),
                ('tipocto', models.CharField(blank=True, help_text='Tipo de CTO', max_length=55)),
                ('direccioncto', models.CharField(blank=True, help_text='Dirección de ubicación del CTO', max_length=255)),
                ('tipopermiso', models.CharField(blank=True, help_text='Tipo de permiso o instalación', max_length=50)),
                ('tipocajaderivacion', models.CharField(blank=True, help_text='Tipo de caja de derivación', max_length=16)),
                ('numunidadesinmobiliarias', models.CharField(blank=True, help_text='Número de unidades inmobiliarias', max_length=3)),
                ('numviviendas', models.CharField(blank=True, help_text='Número de viviendas', max_length=3)),
                ('fechaalta', models.CharField(blank=True, help_text='Fecha de alta en formato AAAAMMDD', max_length=10)),
                ('codigocajaderivacion', models.CharField(blank=True, help_text='Código de caja de derivación / Estado operacional', max_length=50)),
                ('ubicacioncajaderivacion', models.CharField(blank=True, help_text='Ubicación de la caja de derivación / Parcela catastral', max_length=255)),
                ('coinv', models.CharField(blank=True, help_text='Código de inversión o proyecto', max_length=10)),
                ('area_comercial', models.CharField(blank=True, help_text='Área comercial', max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=8, help_text='Coordenada de latitud', max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=8, help_text='Coordenada de longitud', max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Línea de Huella',
                'verbose_name_plural': 'Líneas de Huella',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['iddomicilioto'], name='huella_app__iddomic_63212d_idx'), models.Index(fields=['codigopostal', 'provincia'], name='huella_app__codigop_b1fef8_idx'), models.Index(fields=['codigoolt'], name='huella_app__codigoo_4f6574_idx'), models.Index(fields=['codigocto'], name='huella_app__codigoc_bd22fd_idx')],
            },
        ),
    ]
