# Generated by Django 4.2.27 on 2026-01-18 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('huella_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InePoblacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia_id', models.CharField(max_length=2)),
                ('municipio_id', models.CharField(max_length=3)),
                ('unidad_poblacional', models.CharField(help_text='Código de unidad poblacional (Ej: 000000)', max_length=7)),
                ('nombre', models.CharField(max_length=150)),
                ('total', models.IntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name': 'INE Población',
                'indexes': [models.Index(fields=['provincia_id', 'municipio_id', 'unidad_poblacional'], name='huella_app__provinc_c3fd86_idx')],
            },
        ),
        migrations.CreateModel(
            name='IneMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_provincia', models.CharField(help_text='CPRO (Ej: 01)', max_length=2)),
                ('cod_municipio', models.CharField(help_text='CMUN (Ej: 001)', max_length=3)),
                ('digito_control', models.CharField(help_text='DC', max_length=1)),
                ('nombre_oficial', models.CharField(help_text='NOMBRE', max_length=100)),
            ],
            options={
                'verbose_name': 'INE Municipio',
                'indexes': [models.Index(fields=['cod_provincia', 'cod_municipio'], name='huella_app__cod_pro_a3da69_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportacionHuella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichero_original', models.FileField(upload_to='cargas/originales/')),
                ('fichero_errores', models.FileField(blank=True, null=True, upload_to='cargas/errores/')),
                ('fichero_normalizado', models.FileField(blank=True, null=True, upload_to='cargas/normalizados/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error en validación')], default='PENDIENTE', max_length=20)),
                ('log_proceso', models.TextField(blank=True, help_text='Log detallado del proceso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importación de Huella',
                'verbose_name_plural': 'Importaciones de Huella',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
